let domain = "http://25.59.188.46:8080"

export default {
  login: `${domain}/api/v1/auth/authenticate`,
  register: `${domain}/api/v1/auth/register`,
  role: `${domain}/api/v1/auth/user-role`,
  joinCourse: (courseID) =>  `${domain}/api/v1/student/course/${courseID}/join`,
  completeRegistrationTeacher: `${domain}/api/v1/educator/profile/create`,
  completeRegistrationStudent: `${domain}/api/v1/student/profile/create`,
  coursesTeacher: `${domain}/api/v1/educator/courses`,
  coursesStudent: `${domain}/api/v1/student/courses`,
  createCourse: `${domain}/api/v1/educator/course/create`,
  editCourse: (courseID) => `${domain}/api/v1/educator/course/${courseID}/edit`,
  courseByIDTeacher: (courseID) => `${domain}/api/v1/educator/course/${courseID}`,
  courseByIDStudent: (courseID) => `${domain}/api/v1/student/course/${courseID}`,
  deleteCourseStart: `${domain}/api/v1/educator/course/${"courseID"}/delete`,
  profileTeacher: `${domain}/api/v1/educator/profile`,
  profileStudent: `${domain}/api/v1/student/profile`,
  profileTeacherEdit: `${domain}/api/v1/educator/profile/edit`,
  profileStudentEdit: `${domain}/api/v1/student/profile/edit`,
  assignmentTeacher: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}`,
  assignmentStudent: (courseID, assignmentID) => `${domain}/api/v1/student/course/${courseID}/task/${assignmentID}`,
  deleteAssignment: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}/delete`,
  assignmentAnswers: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}/students`,
  submitAnswer: (courseID, assignmentID) => `${domain}/api/v1/student/course/${courseID}/task/${assignmentID}`,
  submittedAnswer: (courseID, assignmentID) => `${domain}/api/v1/student/course/${courseID}/task/${assignmentID}/passed`,
  deleteSubmittedAnswer: (courseID, assignmentID) => `${domain}/api/v1/student/courses/${courseID}/task/${assignmentID}/delete`,
  uploadAnswerFile: (courseID, assignmentID) => `${domain}/api/v1/student/course/${courseID}/task/${assignmentID}/upload`,
  createAssingment: (courseID) => `${domain}/api/v1/educator/course/${courseID}/task/create`,
  editAssingment: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}/edit`,
  uploadAssignmentFile: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}/upload`,
  downloadAssignmentFile: (courseID, assignmentID) => `${domain}/api/v1/student/courses/${courseID}/task/${assignmentID}/download`, //courses -> course once fixed
  downloadReport: (courseID, studentID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/student/${studentID}/task/${assignmentID}/download`,
  baseFilesChecks: `${domain}/api/v1/educator/course/1/student/1/lab/4/check-basic-files`,
  filesToCheckAdd: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}/file-to-check/add`,
  commitsActivity: (courseID, studentID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/student/${studentID}/task/${assignmentID}/commits`,
  studentAnswer: (courseID, studentID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/student/${studentID}/task/${assignmentID}`,
  gradeAnswer: (courseID, studentID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/student/${studentID}/task/${assignmentID}`,
  courseStudents: (courseID) => `${domain}/api/v1/educator/course/${courseID}/students`,
  courseStatistics: (courseID) => `${domain}/api/v1/educator/course/${courseID}/stats`,
}
