let domain = "http://25.59.188.46:8080"

export default {
  login: `${domain}/api/v1/auth/authenticate`,
  register: `${domain}/api/v1/auth/register`,
  role: `${domain}/api/v1/auth/user-role`,
  joinCourse: (courseID) =>  `${domain}/api/v1/student/course/${courseID}/join`,
  completeRegistrationTeacher: `${domain}/api/v1/educator/profile/create`,
  completeRegistrationStudent: `${domain}/api/v1/student/profile/create`,
  coursesTeacher: `${domain}/api/v1/educator/courses`,
  coursesStudent: `${domain}/api/v1/student/courses`,
  createCourse: `${domain}/api/v1/educator/course/create`,
  editCourse: (courseID) => `${domain}/api/v1/educator/course/${courseID}/edit`,
  courseByIDTeacher: (courseID) => `${domain}/api/v1/educator/course/${courseID}`,
  courseByIDStudent: (courseID) => `${domain}/api/v1/student/course/${courseID}`,
  deleteCourseStart: `${domain}/api/v1/educator/course/${"courseID"}/delete`,
  profilePersonalTeacher: `${domain}/api/v1/educator/profile`,
  profilePersonalStudent: `${domain}/api/v1/student/profile`,
  profilePersonalTeacherEdit: `${domain}/api/v1/educator/profile/edit`,
  profilePersonalStudentEdit: `${domain}/api/v1/student/profile/edit`,
  provideGHAccessTeacher: `${domain}/api/v1/educator/github/provide-access`,
  provideGHAccessStudent: `${domain}/api/v1/student/github/provide-access`,
  saveGHAccessTeacher: `${domain}/api/v1/educator/github/save-access-token`,
  saveGHAccessStudent: `${domain}/api/v1/student/github/save-access-token`,
  createAssignmentRepoTeacher: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}/repo/create`,
  createAssignmentRepoStudent: (courseID, assignmentID) => `${domain}/api/v1/student/course/${courseID}/task/${assignmentID}/repo/create`,
  importAssignmentRepoStudent: (courseID, assignmentID) => `${domain}/api/v1/student/course/${courseID}/task/${assignmentID}/repo/import`,
  profileStudentOnCourse: (courseID, userID) => `${domain}/api/v1/educator/course/${courseID}/students/${userID}`,
  profileTeacherOnCourse: (courseID) => `${domain}/api/v1/student/course/${courseID}/educator-profile`,
  assignmentTeacher: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}`,
  assignmentStudent: (courseID, assignmentID) => `${domain}/api/v1/student/course/${courseID}/task/${assignmentID}`,
  deleteAssignment: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}/delete`,
  assignmentAnswers: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}/students`,
  submitAnswer: (courseID, assignmentID) => `${domain}/api/v1/student/course/${courseID}/task/${assignmentID}`,
  submittedAnswer: (courseID, assignmentID) => `${domain}/api/v1/student/course/${courseID}/task/${assignmentID}/passed`,
  deleteSubmittedAnswer: (courseID, assignmentID) => `${domain}/api/v1/student/courses/${courseID}/task/${assignmentID}/delete`,
  uploadAnswerFile: (courseID, assignmentID) => `${domain}/api/v1/student/course/${courseID}/task/${assignmentID}/upload`,
  createAssingment: (courseID) => `${domain}/api/v1/educator/course/${courseID}/task/create`,
  editAssingment: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}/edit`,
  uploadAssignmentFile: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}/upload`,
  downloadAssignmentFile: (courseID, assignmentID) => `${domain}/api/v1/student/courses/${courseID}/task/${assignmentID}/download`, //courses -> course once fixed
  downloadReport: (courseID, studentID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/student/${studentID}/task/${assignmentID}/download`,
  filesToCheckAdd: (courseID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/task/${assignmentID}/file-to-check/add`,
  repoActivity: (courseID, studentID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/student/${studentID}/task/${assignmentID}/commits`,
  allReposActivity: (courseID, studentID) => `${domain}/api/v1/educator/course/${courseID}/student/${studentID}/all-commits`,
  studentAnswer: (courseID, studentID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/student/${studentID}/task/${assignmentID}`,
  gradeAnswer: (courseID, studentID, assignmentID) => `${domain}/api/v1/educator/course/${courseID}/student/${studentID}/task/${assignmentID}`,
  courseStudents: (courseID) => `${domain}/api/v1/educator/course/${courseID}/students`,
  courseStatistics: (courseID) => `${domain}/api/v1/educator/course/${courseID}/stats`,
}
